### ISSUE TITLE
注册显示400错误

### ISSUE THREAD

**Issue by 2020-mmm-dev** [asiL-tcefreP/blog#1]
JSON parse error: Unrecognized token 'hMqwjCVaLp8bbBHnw8je5S0ZW': was expecting ('true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'hMqwjCVaLp8bbBHnw8je5S0ZW': was expecting ('true', 'false' or 'null')
 at [Source: (PushbackInputStream); line: 1, column: 27]

这个是什么错误呢

**Comment by 2020-mmm-dev** [comment]
刚看了一下，是头像传入问题

**Comment by 2020-mmm-dev** [comment]
请求 URL: https://10.72.177.171:8080/sockjs-node/info?t=1625039641836  控制台显示这个接口调用失败，有什么解决方法吗

**Comment by asiL-tcefreP** [comment]
头像url如果填的是网址，不要写太长，否则会报错

**Comment by 2020-mmm-dev** [comment]
嗯，还有一个问题sockjs-node这一个 JavaScript库 禁用掉对项目功能有影响吗

**Comment by asiL-tcefreP** [comment]
应该是没影响的
