### ISSUE TITLE
屏幕为4k 27寸 会掩盖评论

### ISSUE THREAD

**Issue by topsuder** [asiL-tcefreP/blog#5]
![image](https://user-images.githubusercontent.com/69955165/158933437-16e9ed5e-b2da-430c-a4b7-74197a97360d.png)
![image](https://user-images.githubusercontent.com/69955165/158933489-40280f2f-6fdf-470f-95a9-5536b6edb294.png)

**Comment by asiL-tcefreP** [comment]
感谢指正，前端的自适应做的不够完善，后续有时间会更正
