### ISSUE TITLE
大佬 这几个文件可以分享下么[vecmodel] doesn't exist

### ISSUE THREAD

**Issue by xichuanwushao** [asiL-tcefreP/blog#6]
![Uploading image.png…]()
org.nd4j.linalg.exception.ND4JIllegalStateException: File [F:\usr\local\crawler\article.vecmodel] doesn't exist
大佬 这几个文件可以分享下么 maven install报错找不见这几个文件
  dataPath: G:\repository\crawler #爬取下来的文章的分词文本
  wordLib: G:\repository\crawler\article.txt  #合并后的分词语料库
  vecModel: G:\repository\crawler\article.vecmodel #词向量模型
  cnnModel: G:\repository\crawler\article.cnnmodel  #神经网络卷积模型

**Comment by asiL-tcefreP** [comment]
博客首页q群里有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "asiL-tcefreP/blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 中午11:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[asiL-tcefreP/blog] 大佬 这几个文件可以分享下么[vecmodel] doesn't exist (Issue #6)





 

 org.nd4j.linalg.exception.ND4JIllegalStateException: File [F:\usr\local\crawler\article.vecmodel] doesn't exist
 大佬 这几个文件可以分享下么 maven install报错找不见这几个文件
 dataPath: G:\repository\crawler #爬取下来的文章的分词文本
 wordLib: G:\repository\crawler\article.txt  #合并后的分词语料库
 vecModel: G:\repository\crawler\article.vecmodel #词向量模型
 cnnModel: G:\repository\crawler\article.cnnmodel  #神经网络卷积模型

**Comment by xichuanwushao** [comment]
![image](https://user-images.githubusercontent.com/59530457/165901416-b30e26c7-57ad-4acd-a031-d1f795a0dd34.png)
https://www.tcefrep.site/home网址的博客聊天室的群么

**Comment by asiL-tcefreP** [comment]
链接: https://pan.baidu.com/s/1rXsOnsuGF3kvkOSCdcC-Cw 提取码: 6666
